### ISSUE TITLE
Cant login 

### ISSUE THREAD

**Issue by sehgal15** [aic-factcheck/fact_checking_fe#4]
I am trying to login and get the following API error for some reason:

`undefined/auth/login:1          Failed to load resource: the server responded with a status of 404 (Not Found)`

looks like the login API endpoint is not correct?

**Comment by rastislavkopal** [comment]
Hello. You can generate whole API Docs using `yarn docs`, then open the `./docs/index.html` file with list of all api endpoints with required params and responses.
The correct endpoint for login is:
`base_url/v1/auth/login` (email and password are required params., base_url in my dev case is `localhost:3000`)
So in my case: `https://localhost:3000/v1/auth/login`

**Comment by sehgal15** [comment]
Thanks!
